baseURL = 'https://harmonious-fudge-3ff63b.netlify.app/'
languageCode = 'en-us'
title = 'KSCU Fall Schedule'
theme = "PaperMod"

[params]
disableThemeToggle = false


[params.homeInfoParams]
title = ''
content = ''
