[build]
command = "hugo --gc --minify -b $URL"
publish = "public"
functions = "netlify/functions/"

[dev]
framework = "hugo"
command = "hugo server -D"
publish = "public"
port = 8888
targetPort = 9888
